package config

import (
	"crypto/rand"
	"encoding/hex"
	"fmt"
	"io"
	"os"

	yaml "gopkg.in/yaml.v2"
)

type Config struct {
	ListenAddress  string               `yaml:"listen_address"`
	DatabaseURL    string               `yaml:"database_url"`
	BasePath       string               `yaml:"base_path"`
	SessionKey     string               `yaml:"session_key"`
	keybytes       []byte               `yaml:"-"`
	MaxAge         int                  `yaml:"session_max_age"`
	AutoShutdown   bool                 `yaml:"auto_shutdown"`
	FileStore      FileStoreConfig      `yaml:"file_store"`
	SearchProvider SearchProviderConfig `yaml:"search_provider"`
	Auths          []AuthConfig         `yaml:"authentication"`
}

func (c *Config) SessionKeyBytes() []byte {
	return c.keybytes
}

type FileStoreConfig struct {
	Type  string                 `yaml:"type"`
	Attrs map[string]interface{} `yaml:",inline"`
}

type AuthConfig struct {
	Type  string                 `yaml:"type"`
	Attrs map[string]interface{} `yaml:",inline"`
}

type SearchProviderConfig struct {
	Type  string                 `yaml:"type"`
	Attrs map[string]interface{} `yaml:",inline"`
}

func New() (*Config, error) {
	cfg := &Config{
		ListenAddress: "127.0.0.1:8080",
		DatabaseURL:   "postgres://localhost",
		BasePath:      "/",
		MaxAge:        86400, // Default of 24 hours
	}

	// Set default session key (autogenerated)
	cfg.keybytes = make([]byte, 32)
	_, err := rand.Read(cfg.keybytes)
	if err != nil {
		return nil, err
	}

	// Set default file store (dir, current working directory)
	if cwd, err := os.Getwd(); err == nil {
		cfg.FileStore.Type = "dir"
		cfg.FileStore.Attrs = map[string]interface{}{
			"path": cwd,
		}
	}

	// Set default authentication scheme to file
	cfg.Auths = []AuthConfig{AuthConfig{Type: "file"}}

	return cfg, nil
}

func Load(cpath string) (*Config, error) {
	if cpath == "" {
		searchpaths := []string{"/etc/gmc.yaml"}
		if cdir, err := os.UserConfigDir(); err == nil {
			searchpaths = append(
				searchpaths, cdir+string(os.PathSeparator)+"gmc.yaml",
			)
		}
		searchpaths = append(searchpaths, "gmc.yaml")

		for _, sp := range searchpaths {
			if _, err := os.Stat(sp); err == nil {
				cpath = sp
				break
			}
		}
	}

	cfg, err := New()
	if err != nil {
		return nil, err
	}

	if cpath != "" {
		f, err := os.Open(cpath)
		if err != nil {
			return nil, err
		}

		cdata, err := io.ReadAll(f)
		if err != nil {
			return nil, err
		}

		err = yaml.UnmarshalStrict(cdata, &cfg)
		if err != nil {
			return nil, err
		}

		if cfg.SessionKey != "" {
			b, err := hex.DecodeString(cfg.SessionKey)
			if err != nil || len(b) != 32 {
				return nil, fmt.Errorf(
					"session_key must be exactly 64 hexidecimal characters",
				)
			}

			cfg.keybytes = b
		}
	}

	return cfg, nil
}
